# Generated by Django 2.2 on 2020-11-27 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201127_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='admin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='staff',
        ),
    ]
